### ISSUE TITLE
Documentation/Example request on how to use custom-fonts-in-emails

### ISSUE THREAD

**Issue by katp4** [niftylettuce/email-templates#362]
Hello,

I'm trying to add custom fonts to my emails. I've included the .otf files in my directory, i've installed 
custom-fonts-in-emails but the only thing mentioned in the documentation is to add it to my config.locals which is very vague.

Could you be able to add more documentation or at least an example on how to do that?

Thanks

**Comment by harveyconnor** [comment]
You can use custom fonts in your css.

includes/style.css
```css
@font-face {
  font-family: 'Roboto';
  src: url('../../../assets/fonts/Roboto.otf') format('opentype')
}

body {
  font-family: 'Roboto', Arial, Helvetica, sans-serif;
}
```

And in your html file
html.pug
```pug
head
  style
    include includes/style.css
```
